# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZZStoreKitEx' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZZStoreKitEx


  #pod 'ZZStoreKit', :path => '../../'


  pod 'ZZStoreKit', :git => 'https://github.com/CZ410/ZZStoreKit.git'



  target 'ZZStoreKitExTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZZStoreKitExUITests' do
    # Pods for testing
  end

end
